### ISSUE TITLE
pydantic.v1.error_wrappers.ValidationError

### ISSUE THREAD

**Issue by AveZorgen** [tonkeeper/pytonapi#10]
I'v got an error:
```
Error: 1 validation error for Trace
children -> 0 -> transaction -> out_msgs -> 1 -> init -> library
field required (type=value_error.missing) on tx 6fa11e0361f5a981724dc44de172464884746d7d1d72f25a5fe3e251b7727658
```
One of `out_msgs` field didn't have an field `init` at all but usually does (for example in  a4a644cad11d72a8b6a9fc1537488e7d5d9c11aec6f18e17a43d6d96ea4c925c `init` just `null`)

**Comment by nessshon** [comment]
@AveZorgen, I'm not entirely sure what the error is. I tried running the `tonapi.traces.get_trace` method with the identifier `a4a644cad11d72a8b6a9fc1537488e7d5d9c11aec6f18e17a43d6d96ea4c925c` and didn't encounter any issues.

**Comment by zenoize** [comment]
fixed this bug:
`class Message(BaseModel):
---->    init: Optional[StateInit]`

**Comment by nessshon** [comment]
@AveZorgen 
Understood the issue. Previously, the StateInit schema included the following fields:
```python
class StateInit(BaseModel):
    code: Optional[str]
    data: Optional[str]
    library: Dict[str, str]
```
Now it has changed and includes only one field:
```python
class StateInit(BaseModel):
    boc: str
```

Updated in version `0.2.9`
