### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by mengmengmengqiang** [tonkeeper/pytonapi#13]
python version 3.8.19

plz generate your full requirements.txt file sir.

**Comment by nessshon** [comment]
@mengmengmengqiang,
Hello! Thank you for your feedback. I'll address this issue in the next update. The problem arose because I forgot to use type annotations, which are required for Python versions below 3.10.

**Comment by nessshon** [comment]
@mengmengmengqiang, Try installing version 0.2.8
```bash
pip install pytonapi==0.2.8
```

**Comment by mengmengmengqiang** [comment]
hi there, I query transaction data using lt to offset, but it does not
works.
Below is the python code.

# limit = 1000
# after_lt, 初始为0，用来从上一次拉取的数据后进行拉取
# 每次拉取完交易历史数据以后，根据 lt 对数据进行升序处理，最大的 lt 作为下一次拉取数据的 after_lt
# 循环停止条件：拉取到的 len(transactions) < limit，代表数据已经拉取完成

# 批量写出：当拉取到的数据满足 batch 条时，将数据导出为 excel，并且将缓存池清空

limit = 100
batch = 1e8
after_lt = 0
transactions = []

while len(transactions) < batch:
    print('after_lt', after_lt)
    result =
tonapi.blockchain.get_account_transactions(account_id=account_id,
limit=limit, after_lt=after_lt)

    # sort by lt desc
    result.transactions.sort(key=operator.attrgetter('lt'))

    temp_transactions = result.transactions
    print('temp_transactions:', len(temp_transactions))

    # 没取到数据则结束
    if len(temp_transactions) <= 0:
        break

    transactions.extend(temp_transactions)
    print('transactions:', len(transactions))

    # update params
    after_lt = temp_transactions[-1].lt
    print('after_lt', after_lt)
