### ISSUE TITLE
KeyError: 'logger' when calling a method consecutively

### ISSUE THREAD

**Issue by MBakhshi96** [tonkeeper/pytonapi#25]
I'm getting an error when calling `tonapi.jettons.get_holders` inside a for loop for several addresses, in the second call. The problem is with `__getattributes` and specifically with `attributes.pop("logger")` which raises `KeyError: 'logger'` in the second call. To note here, I've created a `Tonapi` instance outside the loop and am using that for all of the calls. I supposed this is the way it should be used.

**Comment by nessshon** [comment]
@MBakhshi96 Hi! Fixed in version 0.3.9.
