### ISSUE TITLE
Update schema

### ISSUE THREAD

**Issue by awesomes86** [tonkeeper/pytonapi#26]
schema/events.py

class ValueFlowJettonsInner(BaseModel):
    account: AccountAddress
    quantity: int

class ValueFlow(BaseModel):
    account: AccountAddress
    ton: int
    fees: int
    jettons: Optional[List[ValueFlowJettonsInner]] = None
    
    
 For web api compatibility, need add new field to ValueFlowJettonsInner class
 jetton: JettonPreview

**Comment by nessshon** [comment]
@awesomes86 Thank you for your feedback! The update is available in version 0.4.0.
