### ISSUE TITLE
lack of raw_body property in Message schema

### ISSUE THREAD

**Issue by maloleg** [tonkeeper/pytonapi#3]
Hi! Are there any potential pitfalls with adding the "raw_body" property to the Message class in schemas? Not to make any additional requests to tonapi when raw body is actually needed. As i understand its just [one line addition](https://github.com/maloleg/pytonapi/commit/5056b3eeebe6f7cf47cfae2b7104191063852ddf). Could you please add it? Or i can make a pr if you wish.

**Comment by RichardTry** [comment]
Yes guys please!!! I also have been needing this feature for a long time!!!
