### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by mrmajorexe** [tonkeeper/pytonapi#32]
How to send USDT? In the example there is only a code to send TON

**Comment by nessshon** [comment]
@mrmajorexe, to send messages to the blockchain, it's recommended to use `tonutils` with `tonapi`.

For example, to transfer jettons, refer to this example: [Transfer Jetton](https://github.com/nessshon/tonutils/blob/main/examples/jetton/transfer_jetton.py).

Make sure to specify the master address of the USDT jetton (`EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs`) and set the decimals (`6`).

For questions unrelated to the tonapi, feel free to ask in the chat: [https://t.me/tondev_eng](https://t.me/tondev_eng)
