### ISSUE TITLE
Someone has accessed my wallet

### ISSUE THREAD

**Issue by mohammadjavad1375** [tonkeeper/pytonapi#34]
Hello, someone got access to my wallet, I don't know what they did, I transfer all your coins to my wallet and it goes to another account. I would appreciate it if someone could help me.

**Comment by Andesxtzgerald** [comment]
> Hello, someone got access to my wallet, I don't know what they did, I transfer all your coins to my wallet and it goes to another account. I would appreciate it if someone could help me.

Hello @mohammadjavad1375 
We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
I’ll need to refer you to the official support live chat, where you can use the ticket ID WLL6463 for recovery guidelines. 
Please use the following link to access our dedicated support line: 
[Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards
