### ISSUE TITLE
JSONDecodeError on client.blockchain.send_message method

### ISSUE THREAD

**Issue by argentumaurum-eth** [tonkeeper/pytonapi#6]
> Traceback (most recent call last):
>   File "/Users/username/app/venv/lib/python3.11/site-packages/pytonapi/async_tonapi/client.py", line 64, in __read_content
>     content = response.json()
>               ^^^^^^^^^^^^^^^
>   File "/Users/username/app/venv/lib/python3.11/site-packages/httpx/_models.py", line 764, in json
>     return jsonlib.loads(self.content, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/username/app/main.py", line 124, in <module>
>     asyncio.run(main_loop())
>   File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/Users/username/app/main.py", line 119, in main_loop
>     print(await client.blockchain.send_message({'boc': boc}))
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/username/app/venv/lib/python3.11/site-packages/pytonapi/async_tonapi/methods/blockchain.py", line 238, in send_message
>     response = await self._post(method=method, body=body)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/username/app/venv/lib/python3.11/site-packages/pytonapi/async_tonapi/client.py", line 264, in _post
>     return await request("POST", method, headers, params=params, body=body)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/username/app/venv/lib/python3.11/site-packages/pytonapi/async_tonapi/client.py", line 187, in _request
>     return await self.__process_response(response)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/username/app/venv/lib/python3.11/site-packages/pytonapi/async_tonapi/client.py", line 80, in __process_response
>     content = await self.__read_content(response)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/username/app/venv/lib/python3.11/site-packages/pytonapi/async_tonapi/client.py", line 68, in __read_content
>     raise TONAPIError(f"Failed to read response content: {e}")
> pytonapi.exceptions.TONAPIError: Failed to read response content: Expecting value: line 1 column 1 (char 0)

python3.6.11
pytonapi=0.2.3

**Comment by nessshon** [comment]
@argentumaurum-eth, Hi! Can you send me an example of the boc generation code in private messages @nessshon? And you can look at the example https://github.com/tonkeeper/pytonapi/issues/4

**Comment by argentumaurum-eth** [comment]
@nessshon The message was successfully delivered. I think the problem here is the response processing in the latest update. Judging by the documentation endpoint '/v2/blockchain/message' does not return any data in the response except status code on success.
https://github.com/tonkeeper/pytonapi/commit/39ed2e0679efbd6687aeb6a39bf757a163a5af34#diff-ff741cb00eda6938fae428b4b679cfaf6347308a855c6462116369595086d92d

**Comment by nessshon** [comment]
@argentumaurum-eth, try updating the version to 0.2.4 and try again.

**Comment by argentumaurum-eth** [comment]
Thank you!

**Comment by argentumaurum-eth** [comment]
Thank you!

**Comment by nessshon** [comment]
@argentumaurum-eth, And thank you for the feedback!
