### ISSUE TITLE
tx hash in send message

### ISSUE THREAD

**Issue by shirani98** [tonkeeper/pytonapi#7]
Hello
How can I access the transaction hash created by the send message function?

**Comment by nessshon** [comment]
@shirani98, Hello!

Unfortunately, the send message function does not provide access to the transaction hash. Having studied the API documentation (/v2/blockchain/message), it becomes clear that this method does not return any data. You need to come up with alternative methods or approaches to obtain the transaction hash.

**Comment by Sajjad-Khoshdooni** [comment]
> Hello How can I access the transaction hash created by the send message function?

use this api

https://toncenter.com/api/v2/#/send/send_boc_return_hash_sendBocReturnHash_post
