### ISSUE TITLE
SSE with multiple accounts looks suspicious

### ISSUE THREAD

**Issue by AveZorgen** [tonkeeper/pytonapi#9]
Subscription request on transactions is as follows:
`GET https://tonapi.io/v2/sse/accounts/transactions?accounts=UQD0g_SvxCFDL6siKlAbCGuunZY8R7L6imTN0mIaxIGWGVQf&accounts=UQDcJtaekVgLY5kU55mOf1-h3Ulv2h8ZDW2Ff84Q4a5Ek_aA`

But TonConsole [docs](https://docs.tonconsole.com/tonapi/streaming-api#real-time-notifications-about-finalized-transactions) says:

> API method GET https://tonapi.io/v2/sse/accounts/transactions?accounts=<list-of-accounts\>&operations=<list-of-operations> takes in a list of account IDs and an optional list of operations.

**Comment by nessshon** [comment]
@AveZorgen, I'll include this in the next release. At the time of writing the SSE methods, the documentation did not mention the "operations" parameter.

**Comment by AveZorgen** [comment]
I meant that the Accounts request parameter in practice does not actually look like a comma-separated list of accounts

**Comment by nessshon** [comment]
@AveZorgen, thx, changed this in version [0.2.5](https://github.com/tonkeeper/pytonapi/releases/tag/v0.2.5). 
But I forgot to change the other SSE methods... I will change them in the next release.
